# Generated by Django 5.2.4 on 2025-09-12 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'ordering': ['specialty'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('crm', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.specialties')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.profile')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prognostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prognostic', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.profile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patients')),
            ],
            options={
                'verbose_name': 'Prognostic',
                'verbose_name_plural': 'Prognostics',
                'ordering': ['prognostic'],
            },
        ),
        migrations.AddIndex(
            model_name='patients',
            index=models.Index(fields=['doctor'], name='doctor_pati_doctor__69856e_idx'),
        ),
        migrations.AddIndex(
            model_name='patients',
            index=models.Index(fields=['-updated_at'], name='doctor_pati_updated_960152_idx'),
        ),
        migrations.AddIndex(
            model_name='patients',
            index=models.Index(fields=['name'], name='doctor_pati_name_9b4650_idx'),
        ),
        migrations.AddIndex(
            model_name='prognostics',
            index=models.Index(fields=['doctor'], name='doctor_prog_doctor__0a6106_idx'),
        ),
        migrations.AddIndex(
            model_name='prognostics',
            index=models.Index(fields=['patient'], name='doctor_prog_patient_7cde36_idx'),
        ),
        migrations.AddIndex(
            model_name='prognostics',
            index=models.Index(fields=['-updated_at'], name='doctor_prog_updated_f5be84_idx'),
        ),
        migrations.AddIndex(
            model_name='prognostics',
            index=models.Index(fields=['prognostic'], name='doctor_prog_prognos_2e963c_idx'),
        ),
    ]
