# Generated by Django 5.2.4 on 2025-09-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_profile_cpf_alter_profile_crm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
