# Generated by Django 5.2.4 on 2025-09-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
