# Generated by Django 5.2.4 on 2025-10-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_patients_doctor_alter_prognostics_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prognostics',
        ),
    ]
