# Generated by Django 5.2.4 on 2025-10-08 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0006_delete_prognostics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prontuarios', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patients')),
            ],
            options={
                'verbose_name': 'Prontuario',
                'verbose_name_plural': 'Prontuarios',
                'ordering': ['prontuarios'],
                'indexes': [models.Index(fields=['doctor'], name='prontuarios_doctor__0efe2f_idx'), models.Index(fields=['patient'], name='prontuarios_patient_cdd2a1_idx'), models.Index(fields=['prontuarios'], name='prontuarios_prontua_16a3d6_idx')],
            },
        ),
    ]
