# Generated by Django 5.2.4 on 2025-10-27 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_delete_prognostics'),
        ('prontuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prontuarios',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prontuario', 'verbose_name_plural': 'Prontuarios'},
        ),
        migrations.RemoveIndex(
            model_name='prontuarios',
            name='prontuarios_prontua_16a3d6_idx',
        ),
        migrations.AddIndex(
            model_name='prontuarios',
            index=models.Index(fields=['-created_at'], name='prontuarios_created_61242b_idx'),
        ),
    ]
